# Generated by Django 4.0 on 2022-02-04 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.FloatField(default=0, unique=True),
        ),
    ]
