# Generated by Django 4.0 on 2022-02-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_remove_message_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time']},
        ),
    ]
